
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 68
#define YY_END_OF_BUFFER 69
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[334] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       11,   11,    0,    0,    0,    0,    0,    0,   20,   20,
        0,    0,   69,   67,   66,   66,   34,   67,    1,    1,
        4,   68,    4,   36,   41,   39,   38,   41,   40,   49,
       68,   48,   48,   48,   48,   48,   48,   62,   60,   59,
       61,   64,   63,   68,   57,   56,   68,   55,   53,   54,
       67,   67,   51,    1,    1,   13,    9,   68,    8,   68,
       68,   68,   68,   32,   30,   29,   32,   28,   26,   25,
       27,   24,   23,   20,   68,   20,   21,   20,   20,   22,

       15,   68,   16,   17,    0,    1,    1,    0,   36,   38,
        0,   49,    0,   48,   48,   48,   48,   48,   48,   59,
       65,   56,   58,   55,   53,    0,    0,   51,    1,    1,
       13,    9,    0,    8,    0,    0,    0,    0,    0,   25,
       23,   20,   20,   20,   20,   18,   20,   15,   14,    0,
        0,    1,    0,    0,    0,   48,   48,   48,   48,   48,
       52,    0,    1,    0,    0,    0,    0,    0,   31,    0,
       20,   20,   35,    1,    0,    0,   37,   47,   48,   48,
       48,   48,   48,   50,    1,   10,    0,    0,    0,    0,
        0,   20,   20,    1,    0,    0,   48,   48,   48,   48,

       48,    1,    0,    0,    0,    0,   19,   19,   19,   19,
        1,    0,    0,   48,    0,   48,   48,   48,    1,    0,
        0,    0,    0,   19,   19,   19,   19,   19,   19,   19,
       19,    1,    0,    0,   48,    0,   48,    0,    0,   48,
        1,    0,    0,    0,    0,   19,   19,   19,   19,    1,
        0,    0,   48,    0,    0,    0,   48,    1,    0,    0,
        0,    0,   19,   33,    0,    0,    0,    0,    0,    0,
        0,   43,   46,    0,    0,    0,    0,   12,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   42,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        5,    0,    0,    0,    2,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    7,    0,    0,
       44,   45,    0,    0,    7,    0,    6,    0,    0,    0,
        0,    3,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    5,    6,    1,    7,
        8,    9,    1,   10,   11,    1,   12,   13,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,   16,    1,
       17,   18,    1,    1,   19,   20,   20,   20,   20,   21,
       22,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       23,   23,   23,   23,   24,   23,   25,   26,   27,   27,

       28,   29,   27,   30,   31,   27,   27,   32,   33,   34,
       35,   36,   27,   37,   38,   39,   40,   41,   27,   27,
       42,   27,   43,   44,   45,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[46] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    1,
        1,    1,    3,    4,    1,    1,    1,    1,    5,    5,
        5,    5,    6,    7,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    1,    1,    1
    } ;

static const flex_int16_t yy_base[359] =
    {   0,
        0,   16,   59,   60,   51,   69,  111,    0,  156,    0,
      201,    0,  246,    0,  291,    0,  336,    0,  381,  408,
      449,    0,  490,    0,  533,  576,   48,  456,  621,    0,
      666,    0, 1090, 1091, 1091, 1091, 1091, 1080,    0, 1063,
     1091, 1091, 1072,    0, 1091, 1091,    0, 1071, 1091,  457,
     1081,    0, 1052, 1052, 1048, 1042, 1055, 1091, 1091,    0,
     1091, 1091, 1091, 1063, 1091,    0, 1062,    4,    0, 1091,
     1073, 1058,    0, 1051,   41,  535,    0, 1070,    0, 1041,
     1037, 1032, 1045, 1091, 1091, 1091, 1065, 1091, 1091,    0,
     1091, 1091,    0,  542, 1050,  551, 1091, 1061, 1060, 1091,

        0, 1047, 1091, 1091, 1055,    0, 1026, 1045,    0,    0,
     1044,  542, 1044,    0, 1023, 1024, 1026, 1031, 1018,    0,
     1091,    0, 1091,    7,    0, 1038, 1049,    0, 1028,  430,
      564,    0, 1035,    0, 1014, 1015, 1023, 1010, 1030,    0,
        0,    0,    0, 1039, 1038, 1091,  562,    0, 1091, 1034,
     1030, 1010, 1036,  545, 1023, 1008, 1012,  997,  996, 1003,
     1091, 1026,  455, 1016, 1001,  991,  992,  997, 1091, 1021,
     1020, 1019, 1091,  999,   50,  710, 1091, 1091,  998,  990,
      990,  984,  986, 1091,  407, 1091,  983,  977,  965,  976,
        0,  748,  767,  968,  944,  937,  945,  944,  942,  926,

      935,  432,  934,  918,  930,  918,    0,  571,  588,  786,
      907,  904,  908,  904,  889,  894,  585,  889,  456,  892,
      882,  876,  876,    0,  896,  890,    0,    0,  803,  853,
        0,  830,  826,  823,  816,  815,  829,  597,  835,  821,
      457,  809,  816,  798,  811,  832,    0,    0,  822,  833,
      795,  800,  601,  807,  793,  713,  826,  460,  602,  795,
      787,  811,    0, 1091,  786,  779,  714,  788,  763,  762,
      717, 1091, 1091,  718,  783,  772,  768, 1091,  774,  741,
      721,  746,  741,  722,  729,  722,  709,  739,  732, 1091,
      701,  693,  733,  727,  689,  681,  581,  612,  726,  590,

     1091,  736,  740,  580, 1091,  743,  599,  744,  748,  559,
      780,  554,  527,  775,  781,  544,  808,  538,  525,  809,
     1091, 1091,  817,  537,  609,  450, 1091,  447,  432,   69,
        8, 1091, 1091,  860,  868,  876,  884,  890,  896,  902,
      908,  914,  920,  926,  932,  938,  945,  948,  954,  961,
      968,  976,  983,  984,  991,  998, 1005, 1012
    } ;

static const flex_int16_t yy_def[359] =
    {   0,
      334,  333,  335,  335,  336,  336,  333,    7,  333,    9,
      333,   11,  333,   13,  333,   15,  333,   17,  333,   19,
      336,   21,  333,   23,  337,  337,  336,  336,  333,   29,
      333,   31,  333,  333,  333,  333,  333,  333,  338,  338,
      333,  333,  333,  339,  333,  333,  340,  333,  333,  333,
      333,  341,  341,  341,  341,  341,  341,  333,  333,  342,
      333,  333,  333,  333,  333,  343,  333,  333,  344,  333,
      333,  333,  345,  346,  346,  333,  347,  333,  347,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  348,
      333,  333,  349,  350,  333,  350,  333,   96,   96,  333,

      351,  333,  333,  333,  352,  338,  338,  333,  339,  340,
      333,  333,  333,  341,  341,  341,  341,  341,  341,  342,
      333,  343,  333,  333,  344,  333,  333,  345,  346,  346,
      333,  347,  333,   79,  333,  333,  333,  333,  333,  348,
      349,   96,   96,   96,   96,  333,   96,  351,  333,  352,
      352,  338,  333,  333,  333,  341,  341,  341,  341,  341,
      333,  333,  346,  333,  333,  333,  333,  333,  333,  353,
      147,  147,  333,  338,  333,  333,  333,  333,  341,  341,
      341,  341,  341,  333,  346,  333,  333,  333,  333,  333,
      354,  355,  355,  338,  333,  333,  341,  341,  341,  341,

      341,  346,  333,  333,  333,  333,  356,  357,  357,  357,
      338,  333,  333,  341,  333,  341,  341,  341,  346,  333,
      333,  333,  333,  356,  210,  209,  209,  209,  358,  210,
      210,  338,  333,  333,  341,  333,  341,  333,  333,  341,
      346,  333,  333,  333,  333,  209,  210,  209,  358,  338,
      333,  333,  341,  333,  333,  333,  341,  346,  333,  333,
      333,  333,  209,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,

      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,    0,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333
    } ;

static const flex_int16_t yy_nxt[1137] =
    {   0,
      333,   35,   36,   35,   37,  124,  124,  124,  124,  124,
      124,   38,  134,  134,  332,   35,   34,   35,   36,   35,
       37,   34,   34,   34,   34,   34,   34,   38,   34,   34,
       34,   35,   34,   34,   39,   39,   39,   39,   34,   34,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   40,   39,   34,   34,
       34,   42,   42,   92,  106,  130,   93,   93,   93,   93,
      195,  196,  331,   43,   43,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,

       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   45,   45,   42,   45,   45,   45,   45,   45,   45,
       46,   45,   45,   47,   47,   48,   45,   45,   45,   47,
       47,   47,   47,   45,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   45,   45,   49,   42,   50,   50,   50,
       42,   42,   42,   51,   42,   42,   42,   42,   52,   52,
       42,   50,   42,   42,   52,   52,   52,   52,   42,   42,
       53,   52,   52,   52,   54,   52,   55,   52,   52,   52,
       52,   52,   52,   56,   52,   52,   57,   52,   42,   42,

       42,   58,   58,   42,   58,   58,   58,   58,   58,   58,
       59,   58,   58,   60,   60,   58,   58,   58,   58,   60,
       60,   60,   60,   58,   58,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   58,   58,   61,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   62,   42,   42,   63,   63,
       42,   42,   42,   42,   63,   63,   63,   63,   42,   42,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   42,   42,
       64,   42,   42,   42,   42,   42,   42,   42,   42,   42,

       65,   42,   42,   66,   66,   42,   42,   42,   42,   66,
       66,   66,   66,   42,   42,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   42,   42,   67,   42,   68,   68,   68,
       42,   42,   42,   42,   42,   42,   42,   42,   69,   69,
       42,   70,   42,   42,   69,   69,   69,   69,   42,   42,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   42,   42,
       42,   34,   35,   36,   35,   37,   34,   34,   71,   34,
       34,   72,   38,   73,   73,   34,   35,   34,   34,   73,

       73,   73,   73,   34,   34,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   34,   34,   34,   74,   74,   74,   74,
      106,  202,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   75,   74,
       76,   76,   76,  106,   77,  106,   78,  219,  112,  112,
      112,   77,   77,  264,   76,  330,  163,   79,   79,   79,
       79,   92,  112,   80,   93,   93,   93,   93,  106,  106,
      106,  329,   81,  106,  258,  185,   82,  241,  328,   83,
       84,   84,   42,   84,   84,   84,   84,   84,   84,   85,

       84,   84,   86,   86,   84,   84,   84,   84,   86,   86,
       86,   86,   84,   84,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   84,   84,   87,   42,  131,  131,  131,  325,
      327,  325,   89,  112,  112,  112,  176,  142,  176,  326,
      131,   90,   90,   90,   90,  143,  142,  112,  322,  319,
      144,  144,  144,  144,  143,  131,  131,  131,  318,  144,
      144,  144,  144,  317,  170,  171,  225,   91,   42,  131,
      172,  172,  172,  172,  226,   89,  238,  177,  238,  227,
      227,  227,  227,  225,   90,   90,   90,   90,  238,  239,

      238,  226,  267,  274,  267,  274,  227,  227,  227,  227,
      325,  239,  325,  314,  313,  268,  275,  308,  305,  304,
       91,   42,   42,   42,   42,   42,   94,   42,   42,   42,
       42,   95,   42,   42,   96,   42,   97,   42,   42,   98,
       98,   98,   98,   42,   42,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   42,  100,   42,   42,   42,   42,   42,
       42,  101,   42,   42,   42,   42,  102,   42,   42,  101,
       42,  103,   42,   42,  101,  101,  101,  101,   42,   42,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,

      101,  101,  101,  101,  101,  101,  101,  101,   42,  104,
       42,  176,  303,  176,  271,  267,  271,  267,  271,  274,
      271,  274,  289,  293,  289,  293,  302,  306,  268,  306,
      301,  300,  275,  289,  293,  289,  293,  309,  299,  309,
      307,  311,  298,  311,  306,  315,  306,  315,  297,  309,
      310,  309,  177,  142,  312,  272,  296,  307,  316,  272,
      295,  143,  310,  290,  294,  292,  208,  208,  208,  208,
      207,  207,  142,  291,  290,  294,  320,  288,  320,  170,
      171,  311,  315,  311,  315,  210,  210,  210,  210,  207,
      207,  229,  287,  286,  312,  316,  285,  284,  170,  230,

      283,  282,  281,  280,  231,  231,  231,  231,  246,  323,
      320,  323,  320,  279,  278,  170,  230,  321,  323,  277,
      323,  247,  247,  247,  247,  207,  207,  246,  276,  273,
      270,  269,  266,  265,  333,  226,  264,  246,  262,  261,
      263,  263,  263,  263,  207,  207,  260,  259,  257,  256,
      324,  321,  255,  254,  253,  252,  251,  250,  249,  324,
       34,   34,   34,   34,   34,   34,   34,   34,   41,   41,
       41,   41,   41,   41,   41,   41,   42,   42,   42,   42,
       42,   42,   42,   42,   88,   88,   88,   88,   88,   88,
       88,   88,  106,  106,  106,  246,  106,  106,  109,  109,

      109,  246,  109,  109,  110,  110,  110,  245,  110,  110,
      114,  114,  114,  244,  243,  114,  120,  120,  120,  242,
      240,  120,  122,  122,  122,  237,  236,  122,  125,  125,
      125,  235,  234,  125,  128,  128,  128,  233,  232,  128,
      129,  129,  129,  223,  129,  129,  132,  132,  132,  132,
      140,  140,  140,  222,  221,  140,  141,  141,  141,  220,
      218,  141,  145,  217,  145,  145,  216,  215,  145,  148,
      214,  148,  148,  213,  212,  148,  150,  150,  150,  150,
      150,  150,  150,  150,  170,  170,  170,  170,  207,  207,
      207,  207,  209,  211,  209,  209,  209,  209,  209,  224,

      206,  224,  224,  205,  204,  224,  228,  203,  228,  228,
      201,  200,  228,  248,  248,  248,  248,  248,  248,  248,
      199,  198,  197,  194,  193,  192,  191,  190,  189,  188,
      187,  186,  184,  183,  182,  181,  180,  179,  178,  175,
      174,  173,  151,  147,  147,  169,  168,  167,  166,  165,
      164,  106,  162,  161,  160,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  149,  147,  147,  146,  139,  138,
      137,  136,  135,  133,  106,  127,  126,  123,  121,  119,
      118,  117,  116,  115,  113,  111,  108,  107,  105,  333,
       33,  333,  333,  333,  333,  333,  333,  333,  333,  333,

      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333
    } ;

static const flex_int16_t yy_chk[1137] =
    {   0,
        0,    1,    1,    1,    1,   68,   68,   68,  124,  124,
      124,    1,   79,   79,  331,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    3,    4,   27,   75,   75,   27,   27,   27,   27,
      175,  175,  330,    3,    4,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    6,    6,    6,    6,    6,    6,    6,

        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,

        9,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   15,   15,   15,   15,   15,   15,   15,   15,   15,

       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,

       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   20,   20,   20,   20,
      185,  185,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       21,   21,   21,  130,   21,  202,   21,  202,   50,   50,
       50,   21,   21,  258,   21,  329,  130,   21,   21,   21,
       21,   28,   50,   21,   28,   28,   28,   28,  163,  219,
      241,  328,   21,  258,  241,  163,   21,  219,  326,   21,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,

       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   25,   76,   76,   76,  318,
      324,  318,   25,  112,  112,  112,  154,   94,  154,  319,
       76,   25,   25,   25,   25,   94,   96,  112,  316,  313,
       94,   94,   94,   94,   96,  131,  131,  131,  312,   96,
       96,   96,   96,  310,  147,  147,  208,   25,   26,  131,
      147,  147,  147,  147,  208,   26,  217,  154,  217,  208,
      208,  208,  208,  209,   26,   26,   26,   26,  238,  217,

      238,  209,  253,  259,  253,  259,  209,  209,  209,  209,
      325,  238,  325,  307,  304,  253,  259,  300,  298,  297,
       26,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,

       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,  176,  296,  176,  256,  267,  256,  267,  271,  274,
      271,  274,  281,  284,  281,  284,  295,  299,  267,  299,
      294,  292,  274,  289,  293,  289,  293,  302,  291,  302,
      299,  303,  288,  303,  306,  308,  306,  308,  287,  309,
      302,  309,  176,  192,  303,  256,  286,  306,  308,  271,
      285,  192,  309,  281,  284,  283,  192,  192,  192,  192,
      192,  192,  193,  282,  289,  293,  314,  280,  314,  193,
      193,  311,  315,  311,  315,  193,  193,  193,  193,  193,
      193,  210,  279,  277,  311,  315,  276,  275,  210,  210,

      270,  269,  268,  266,  210,  210,  210,  210,  229,  317,
      320,  317,  320,  265,  262,  229,  229,  314,  323,  261,
      323,  229,  229,  229,  229,  229,  229,  249,  260,  257,
      255,  254,  252,  251,  249,  249,  250,  246,  245,  244,
      249,  249,  249,  249,  249,  249,  243,  242,  240,  239,
      317,  320,  237,  236,  235,  234,  233,  232,  230,  323,
      334,  334,  334,  334,  334,  334,  334,  334,  335,  335,
      335,  335,  335,  335,  335,  335,  336,  336,  336,  336,
      336,  336,  336,  336,  337,  337,  337,  337,  337,  337,
      337,  337,  338,  338,  338,  226,  338,  338,  339,  339,

      339,  225,  339,  339,  340,  340,  340,  223,  340,  340,
      341,  341,  341,  222,  221,  341,  342,  342,  342,  220,
      218,  342,  343,  343,  343,  216,  215,  343,  344,  344,
      344,  214,  213,  344,  345,  345,  345,  212,  211,  345,
      346,  346,  346,  206,  346,  346,  347,  347,  347,  347,
      348,  348,  348,  205,  204,  348,  349,  349,  349,  203,
      201,  349,  350,  200,  350,  350,  199,  198,  350,  351,
      197,  351,  351,  196,  195,  351,  352,  352,  352,  352,
      352,  352,  352,  352,  353,  353,  353,  353,  354,  354,
      354,  354,  355,  194,  355,  355,  355,  355,  355,  356,

      190,  356,  356,  189,  188,  356,  357,  187,  357,  357,
      183,  182,  357,  358,  358,  358,  358,  358,  358,  358,
      181,  180,  179,  174,  172,  171,  170,  168,  167,  166,
      165,  164,  162,  160,  159,  158,  157,  156,  155,  153,
      152,  151,  150,  145,  144,  139,  138,  137,  136,  135,
      133,  129,  127,  126,  119,  118,  117,  116,  115,  113,
      111,  108,  107,  105,  102,   99,   98,   95,   87,   83,
       82,   81,   80,   78,   74,   72,   71,   67,   64,   57,
       56,   55,   54,   53,   51,   48,   43,   40,   38,   33,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,

      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tema.l"
/* Theodhoraq Mihallari 333CC */
#line 4 "tema.l"
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include <ctype.h>

//var = varaibila
//det - deterministic

bool global_var = true;    //var sa stie daca lucram cu variabila globala sau locala 
char name_buffer[50];    //stocham momentan numele automatului/grammatica

//struct global accesabil pentru variabile de ambele tip
typedef struct {
    char identifier[50];  // Nume
    int no_of_domains;    // No de domains
    char domains[20][50]; // numele lor
    bool is_global;       //este global sau local?
    int index; //daca sunt local,ce automat apartin 
    int index_for_grammers; //la fel dar pentru gramaticii
} GlobalVar; 

// Array pentru 100 global variables
GlobalVar globalVars[100];
int globalVarCount = 0; //no de variabile
bool i_am_grammer = false; //bool folosit pentru variabile de gramatici
//am folosit acelas tranzitile (%x IN_VARIABLE) pentru variabile de automat si gramatica
//din asta am acesta variabile,sa sti daca am venit din automat sau gramatica


// Structure pentru traziti
typedef struct {
    char from[20][3];    // from state
    char input[20][10];   // input symbol
    char to[20][3];      // to state
    int count;            // no de trazitii
} AutomatonRules;

//structura pentru automate
typedef struct {
    char name[50];       
    int num_rules;       
    char alphabet[37];   //letters + digits
    int alphabet_count;
    int num_states;
    char final_states[30][3];
    int num_final_states;
    char initial_state[3];
    AutomatonRules rules;
} Automaton;

bool clock = true; //folosit pentru citirea de trazitii (explicat mai jos)
Automaton automatons[50];  
int automatonCount = 0;    
bool flag = false;  //folosit pentru printarea de variabile in trazitii

//functie care primesc un automat si verific daca este det sau non det,explicat in readme
bool isDeterministic(Automaton *a) {
    for (int i = 0; i < a->rules.count; i++) {
        char from_i[3], to_i[3];
        char input_i[50];
        strcpy(input_i,a->rules.input[i]);
        strcpy(from_i, a->rules.from[i]);
        strcpy(to_i, a->rules.to[i]);

        for (int j = i + 1; j < a->rules.count; j++) {
            char from_j[3], to_j[3];
            char input_j[50];
            strcpy(input_j,a->rules.input[j]);
            strcpy(from_j, a->rules.from[j]);
            strcpy(to_j, a->rules.to[j]);

            // Daca 2 tranziti sunt din acelas stare
            if (strcmp(from_i, from_j) == 0) {
                // Check daca inputuri sunt variabile (daca da avem nevoie de domeniu)
                bool input_i_is_var = false, input_j_is_var = false;
                int var_i_index = -1, var_j_index = -1;

                // check daca input_i este o variable
                for (int k = 0; k < globalVarCount; k++) {
                    if (strcmp((char[]){globalVars[k].identifier[0], '\0'},input_i) == 0) {
                        
                        if (globalVars[k].is_global){
                            input_i_is_var = true;
                            var_i_index = k;
                            break;
                        }else {
                            if (automatonCount == globalVars[k].index) {
                                input_i_is_var = true;
                                var_i_index = k;
                                break;
                            }
                        }
                       
                    }
                }

                // check input_j
                for (int k = 0; k < globalVarCount; k++) {
                    if (strcmp((char[]){globalVars[k].identifier[0], '\0'},input_j) == 0) {

                        if (globalVars[k].is_global){
                            input_j_is_var = true;
                            var_j_index = k;
                            break;
                        }else {
                            if (automatonCount == globalVars[k].index) {
                                input_j_is_var = true;
                                var_j_index = k;
                                break;
                            }
                        }
                    }
                }

                // daca sunt variabile 
                if (input_i_is_var || input_j_is_var) {
                    // Expand la domains
                    char expanded_inputs_i[20][50], expanded_inputs_j[20][50];
                    int count_i = 0, count_j = 0;  

                    if (input_i_is_var) {
                        for (int k = 0; k < globalVars[var_i_index].no_of_domains; k++) {
                            strcpy(expanded_inputs_i[count_i++], globalVars[var_i_index].domains[k]);
                        }
                    } else {
                        strcpy(expanded_inputs_i[count_i++],input_i);
                    }

                    if (input_j_is_var) {
                        for (int k = 0; k < globalVars[var_j_index].no_of_domains; k++) {
                            strcpy(expanded_inputs_j[count_j++], globalVars[var_j_index].domains[k]);
                        }
                    } else {
                        strcpy(expanded_inputs_j[count_j++],input_j);
                    }

                    //verificam daca 2 inputuri sunt acelas -> non det
                    for (int x = 0; x < count_i; x++) {
                        for (int y = 0; y < count_j; y++) {
                            if (strcmp(expanded_inputs_i[x], expanded_inputs_j[y]) == 0) {
                                return false; 
                            }
                        }
                    }
                } else {
                    // daca intrarile nu sunt variabile comparam direct simboluri de intrare
                    if (input_i == input_j) {
                        return false; 
                    }
                }
            }
        }
    }
    return true; // Deterministic
}



void printAutomaton(Automaton *a) {
    printf("\nNumele automatului: %s\n", a->name);
  if (isDeterministic(a)) {
        printf("Tipul automatului: Automat finit determinist (DFA)\n");
    } else {
        printf("Tipul automatului: Automat finit nedeterminist (NFA)\n");
    }    
    printf("Alfabetul de intrare: {");
    for(int i = 0; i < a->alphabet_count; i++) {
        printf("%c%s", a->alphabet[i], 
               i < a->alphabet_count - 1 ? ", " : "");
    }
    printf("}\n");
    
    printf("Numarul de stari: %d\n", a->num_states);
    printf("Starile finale: {");
    for(int i = 0; i < a->num_final_states; i++) {
        printf("%s%s", a->final_states[i],i < a->num_final_states - 1 ? ", " : "");
    }
        printf("}\n");
    printf("Starea initiala: %s\n", a->initial_state);
    
    int index = 0; //index pentru variabila (daca este)
    printf("Functia de tranzitie:\n");
    for(int i = 0; i < a->rules.count; i++) {

        for (int j = 0; j < 100; j++) {
//trecem prin vars și vedem daca oricare este egal cu inputul nostru
//latest var declarat și local are prioritate
        if (strcmp((char[]){globalVars[j].identifier[0], '\0'} ,a->rules.input[i]) == 0) {
//daca sunt global ,ok
            if (globalVars[j].is_global){
                flag = true;
                index = j;
            }else {
                //daca nu verificam ca sunt local pentur acest automat
                if(automatonCount == globalVars[j].index) {
                    flag = true;
                    index = j;
                }
            }
         
        }
    }

    if (!flag) {
        printf("m(%s, %s) = %s\n", 
               a->rules.from[i],
               a->rules.input[i],
               a->rules.to[i]);
    } else { 
     for (int k = 0;k < globalVars[index].no_of_domains; k++) {
               printf("m(%s, %s) = %s\n", 
               a->rules.from[i],
               globalVars[index].domains[k],
               a->rules.to[i]);
     }
     flag = false;
    }
   }

//local vars
 for (int i = 0; i < 100; i++) {

        if (globalVars[i].index == automatonCount) {

            printf("Variabila locala:\n");
            printf("  Identificator: %s\n", globalVars[i].identifier);
            
            printf("  Domeniu: {");
            for (int j = 0; j < globalVars[i].no_of_domains; j++) {
            printf("%s%s", globalVars[i].domains[j], (j == globalVars[i].no_of_domains - 1) ? "}" : " ,");
            //if ultimul in loop (pentru printarea)
            }
            printf("\n");
        }
    }

printf("\n");
}

typedef struct {
    char name[50];
    char alphabet[37];   //letters + digits
    int alphabet_count;
    int num_non_term;   //no de non terminali
    char start_symbol[5];
    int no_of_rules;
} Grammer;

Grammer grammers[50]; 
int grammersCount = 0;    
int type[100];  //vector care stocheaza toate tipuri pentru fiecare regula (valorea cel mai mice este tipul de gramatica)
int type_index = 0;  
int len_of_alpha; //pentru  type 0 or 1 ,alpha -> beta  (|alpha| <= |beta|)
int len_of_beta;

void print_grammer_info(Grammer *g) {
    int lowest_type = 4;

    for (int i = 0; i < type_index; i++) {
        if (type[i] < lowest_type) {
            //cel mai mica
            lowest_type  = type[i];
        }
    }
    printf("\n");
    printf("Numele gramaticii: %s\n",g->name);
    printf("Tipul gramaticii: ");
     switch (lowest_type) {
        case 0:
            printf("GN (grammatica neregulata tip 0)\n");
            break;
        case 1:
            printf("GDC (tip 1)\n");
            break;
        case 2:
            printf("GIC (tip 2)\n");
            break;
        case 3:
            printf("GR (tip 3)\n");
            break;
        default:
            printf("ERROR\n");
            break;
    }
    printf("Numarul de reguli de productie: %d\n",g->no_of_rules);
    printf("Alfabetul gramaticii: {");
    for (int i = 0; i < g->alphabet_count; i++) {
        printf("%c%s", g->alphabet[i], (i == g->alphabet_count - 1) ? "}" : " ,");
    }
    printf("\n");

    //local vars
 for (int i = 0; i < 100; i++) {

        if (globalVars[i].index_for_grammers == grammersCount) {

            printf("Variabila locala:\n");
            printf("  Identificator: %s\n", globalVars[i].identifier);
            
            printf("  Domeniu: {");
            for (int j = 0; j < globalVars[i].no_of_domains; j++) {
            printf("%s%s", globalVars[i].domains[j], (j == globalVars[i].no_of_domains - 1) ? "}" : " ,");
            }
            printf("\n");
        }
    }

    //resetam pentru gramatica urmatora
    memset(type, 0, sizeof(type));
    type_index = 0;
}
#line 1121 "lex.yy.c"
 
#line 1123 "lex.yy.c"

#define INITIAL 0
#define IN_GRAMMER_OR_AUTOMAT 1
#define IN_VARIABLE 2
#define IN_VARIABLE2 3
#define IN_AUTOMATON 4
#define IN_COUNT 5
#define IN_ALPHA 6
#define IN_FINAL_STATE 7
#define IN_INITIAL_STATE 8
#define IN_TRANSITIONS 9
#define IN_GRAMMER 10
#define IN_ALPHA2 11
#define IN_NONTERM 12
#define IN_START_SYMBOL 13
#define IN_TYPE_2_3 14
#define IN_TYPE_0_1 15

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state ( int _new_state );
    
    static void yy_pop_state ( void );
    
    static int yy_top_state ( void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 335 "tema.l"



#line 1372 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 334 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1091 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 338 "tema.l"
{
    strcpy(name_buffer,yytext);  //stocham ce am primit
    BEGIN(IN_GRAMMER_OR_AUTOMAT);    //verificam ce este
}
	YY_BREAK

case 2:
YY_RULE_SETUP
#line 344 "tema.l"
{    //daca urmatorul string este asta este grammatice
    strcpy(grammers[grammersCount].name,name_buffer);
    BEGIN(IN_GRAMMER);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 348 "tema.l"
{   //you get the idea :) 
    strcpy(automatons[automatonCount].name,name_buffer);
    BEGIN(IN_AUTOMATON);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 352 "tema.l"
{

}
	YY_BREAK


case 5:
YY_RULE_SETUP
#line 360 "tema.l"
{   //pentru fiecare field facem patter match is stocham 
        grammers[grammersCount].alphabet_count = 0;
        yy_push_state(IN_ALPHA2);
    }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 365 "tema.l"
{
        yy_push_state(IN_NONTERM);
    }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 369 "tema.l"
{
        yy_push_state(IN_START_SYMBOL);
    }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 373 "tema.l"
{  //match cu: O litera mare urmata optional de mai multe cifre 
       //S,S1,S2 .... S222.... aka pot sa fii type 2 or 3 (regulated or contex free)
        type[type_index] = 3;
        type_index++;
        yy_push_state(IN_TYPE_2_3);
    }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 380 "tema.l"
{   //tip 0 sau 1
 
    for (int i = 0; i < yyleng; i++) {
        if (isalpha(yytext[i])) {
            len_of_alpha++;
        }
    }
        yy_push_state(IN_TYPE_0_1);
    }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 389 "tema.l"
{  //am terminat gramatica 
    print_grammer_info(&grammers[grammersCount]);
    grammersCount++;    
	BEGIN(INITIAL);
	} 
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 395 "tema.l"
{

    }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 399 "tema.l"
{  //daca este o var locala
    global_var = false;    
    i_am_grammer = true;
    BEGIN(IN_VARIABLE); 
    }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 404 "tema.l"
;  // Skip whitespace si semicolons
	YY_BREAK


case 14:
YY_RULE_SETUP
#line 409 "tema.l"
{
//ignoram asta
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 414 "tema.l"
{
//pentru fiecare regula verificam conditia |a| <= |b|
     for (int i = 0; i < yyleng; i++) {
        if (isalpha(yytext[i])) {
            len_of_beta++;
        }
    }

    if (len_of_alpha <= len_of_beta) {
        type[type_index] = 1;
        type_index++;
    } else {
      type[type_index] = 0;
       type_index++;
    }
    len_of_beta = 0;

}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 433 "tema.l"
{
    len_of_alpha = 0;  //resetam
    grammers[grammersCount].no_of_rules++;
    yy_pop_state();
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 438 "tema.l"
{
 grammers[grammersCount].no_of_rules++;
}
	YY_BREAK


case 18:
YY_RULE_SETUP
#line 444 "tema.l"
{

}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 448 "tema.l"
{ //daca este de forma ...aSb de exemplu
type[type_index] = 2;
type_index++;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 454 "tema.l"
{
//tip 3
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 458 "tema.l"
{
    grammers[grammersCount].no_of_rules++;
    yy_pop_state();
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 462 "tema.l"
{
 grammers[grammersCount].no_of_rules++;
}
	YY_BREAK


case 23:
YY_RULE_SETUP
#line 469 "tema.l"
{ //stocham ce am primit,la fel pentru alta stari
        strcpy(grammers[grammersCount].start_symbol,yytext);
    }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 473 "tema.l"
{ //am terminat
    yy_pop_state();
   }
	YY_BREAK


case 25:
YY_RULE_SETUP
#line 481 "tema.l"
{
        grammers[grammersCount].num_non_term++;
    }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 484 "tema.l"
{
    }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 486 "tema.l"
{
    yy_pop_state();
    }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 490 "tema.l"
{
	
	 }
	YY_BREAK


case 29:
YY_RULE_SETUP
#line 496 "tema.l"
{ 

        grammers[grammersCount].alphabet[grammers[grammersCount].alphabet_count] = yytext[0]; 
        grammers[grammersCount].alphabet_count++; 
    }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 501 "tema.l"
{ 
    }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 503 "tema.l"
{ 
        yy_pop_state();
    }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 506 "tema.l"
{

    }
	YY_BREAK

case 33:
YY_RULE_SETUP
#line 511 "tema.l"
{ 
    //variabila globala
    BEGIN(IN_VARIABLE); 
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 516 "tema.l"
{
//commentari pe linie
}
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 520 "tema.l"
{
//comentari cu mai mult de randuri
}
	YY_BREAK

case 36:
YY_RULE_SETUP
#line 526 "tema.l"
{ 
        if (global_var) {   //daca global var pritam direct si stocham
            globalVars[globalVarCount].is_global = true;
        printf("Variabila globala:\n");
        strcpy(globalVars[globalVarCount].identifier, yytext);
        printf("  Identificator: %s\n", yytext);
        
        globalVars[globalVarCount].no_of_domains = 0; 
        
        BEGIN(IN_VARIABLE2);   //alte date
    }else if (!global_var) {
        globalVars[globalVarCount].is_global = false;
        if(i_am_grammer){  //daca am venit din o gramatica
            globalVars[globalVarCount].index_for_grammers = grammersCount;
        }else {
        globalVars[globalVarCount].index = automatonCount;

        }
        strcpy(globalVars[globalVarCount].identifier, yytext);
        
        globalVars[globalVarCount].no_of_domains = 0; 
        BEGIN(IN_VARIABLE2); 
    }
        
    }
	YY_BREAK


case 37:
YY_RULE_SETUP
#line 554 "tema.l"
{ 
         if(global_var) {
            printf("  Domeniu: {"); 
        }
    }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 559 "tema.l"
{ 
       //domeniu
        strcpy(globalVars[globalVarCount].domains[globalVars[globalVarCount].no_of_domains], yytext);
        globalVars[globalVarCount].no_of_domains++;
         if(global_var) {
            printf("%s", yytext); 
        }
    }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 567 "tema.l"
{ 
        if(global_var) {
            printf(", ");
        }
    
        }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 573 "tema.l"
{ 
        if(global_var) {
            printf("}\n");
        }
        globalVarCount++; 
        if(!global_var){
            global_var = true;
            if (!i_am_grammer){
                //daca am venit din automat merg inapoi
                BEGIN(IN_AUTOMATON); 

            }else {
                i_am_grammer = false;
                BEGIN(IN_GRAMMER);
            }
  
        }else

        BEGIN(INITIAL); 
    }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 593 "tema.l"
{}
	YY_BREAK


case 42:
YY_RULE_SETUP
#line 597 "tema.l"
{ 
            yy_push_state(IN_ALPHA);
    }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 600 "tema.l"
{
        yy_push_state(IN_COUNT);
    }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 603 "tema.l"
{ 
        yy_push_state(IN_FINAL_STATE);
    }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 606 "tema.l"
{
        yy_push_state(IN_INITIAL_STATE);
    }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 610 "tema.l"
{ 
    global_var = false;
    BEGIN(IN_VARIABLE); 
    }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 615 "tema.l"
{
    printAutomaton(&automatons[automatonCount]);

    automatonCount++;
	BEGIN(INITIAL);
	} 
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 621 "tema.l"
{ 
        //traziti sunt de froma : from input to -> q0 a q1 ,din q0 cu a merg la q1 (de exemplu)
        //asta este pentru stochare de from
        strcpy(automatons[automatonCount].rules.from[automatons[automatonCount].rules.count], yytext);
        BEGIN(IN_TRANSITIONS);
    }
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 628 "tema.l"
; 
	YY_BREAK


case 50:
YY_RULE_SETUP
#line 632 "tema.l"
{

 }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 635 "tema.l"
{
 //acum am stochat from,stochez inputuri si la ce stare merg cu asta
 //prima este inputul din asta stochez inputul primul (clock = true)
 //al doua este "to" (la ce stare merg cu asta,clock = false) 
 //aceste sunt in foram input,to,input,to.... din asta am folosit un clock schema
 //am invatat la apm (verilog) :)
        if(clock){
        
        strcpy(automatons[automatonCount].rules.input[automatons[automatonCount].rules.count] ,yytext);

        }else {
        strcpy(automatons[automatonCount].rules.to[automatons[automatonCount].rules.count],yytext);
        automatons[automatonCount].rules.count++;
        strcpy(automatons[automatonCount].rules.from[automatons[automatonCount].rules.count], automatons[automatonCount].rules.from[automatons[automatonCount].rules.count - 1]);

        }
        //resetam
        clock = !clock;

    }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 656 "tema.l"
{
      BEGIN(IN_AUTOMATON);
    }
	YY_BREAK


case 53:
YY_RULE_SETUP
#line 661 "tema.l"
{
        strcpy(automatons[automatonCount].initial_state ,yytext); 
    }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 664 "tema.l"
{ 
        yy_pop_state();
    }
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 668 "tema.l"
;  
	YY_BREAK


case 56:
YY_RULE_SETUP
#line 672 "tema.l"
{ 
        strcpy(automatons[automatonCount].final_states[automatons[automatonCount].num_final_states] ,yytext); 
        automatons[automatonCount].num_final_states++; 
    }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 676 "tema.l"
{ 
    }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 678 "tema.l"
{ 
        yy_pop_state();
    }
	YY_BREAK


case 59:
YY_RULE_SETUP
#line 685 "tema.l"
{
        //facem count pentru no de stari
        automatons[automatonCount].num_states++;
    }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 689 "tema.l"
{
    }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 691 "tema.l"
{
        yy_pop_state(); 
    }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 695 "tema.l"
{
	
	 }
	YY_BREAK


case 63:
YY_RULE_SETUP
#line 701 "tema.l"
{ 
   
        automatons[automatonCount].alphabet[automatons[automatonCount].alphabet_count] = yytext[0]; 
        automatons[automatonCount].alphabet_count++; 
    }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 706 "tema.l"
{ 
    }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 708 "tema.l"
{ 
        yy_pop_state();
    }
	YY_BREAK

case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 713 "tema.l"
;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 714 "tema.l"
;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 716 "tema.l"
ECHO;
	YY_BREAK
#line 2038 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IN_GRAMMER_OR_AUTOMAT):
case YY_STATE_EOF(IN_VARIABLE):
case YY_STATE_EOF(IN_VARIABLE2):
case YY_STATE_EOF(IN_AUTOMATON):
case YY_STATE_EOF(IN_COUNT):
case YY_STATE_EOF(IN_ALPHA):
case YY_STATE_EOF(IN_FINAL_STATE):
case YY_STATE_EOF(IN_INITIAL_STATE):
case YY_STATE_EOF(IN_TRANSITIONS):
case YY_STATE_EOF(IN_GRAMMER):
case YY_STATE_EOF(IN_ALPHA2):
case YY_STATE_EOF(IN_NONTERM):
case YY_STATE_EOF(IN_START_SYMBOL):
case YY_STATE_EOF(IN_TYPE_2_3):
case YY_STATE_EOF(IN_TYPE_0_1):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 334 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 334 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 333);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        yyfree( (yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 716 "tema.l"


int main(int argc, char *argv[]) {
    if(argc != 2) {
        printf("Usage: %s input_file\n", argv[0]);
        return 1;
    }
    memset(globalVars, -1, sizeof(globalVars));

    yyin = fopen(argv[1], "r");
    yylex();
    return 0;
}
